### ISSUE TITLE
Hierarchical Sorting - Not Working

### ISSUE THREAD

**Issue by danieljfeller** [datavisyn/lineup_htmlwidget#13]
I'm only able to sort on a single column; this is true both on the sidebar and the columns themselves (see image)

BTW this is a fantastic contribution, so thanks!

![image](https://user-images.githubusercontent.com/30907365/62341137-1d47cf80-b4b0-11e9-9b17-e2933e0e86cc.png)

![image](https://user-images.githubusercontent.com/30907365/62341085-dd80e800-b4af-11e9-9d86-6ba5aab689f9.png)

**Comment by sgratzl** [comment]
can you provide some test data, please?

**Comment by danieljfeller** [comment]
@sgratzl I was simply using the iris dataset; this problem seems identical to https://github.com/lineupjs/lineupjs/issues/161

**Comment by sgratzl** [comment]
have you tried adding `, options=list(noCriteriaLimits=TRUE)` when calling LineUp. I checked the code and by default only one sort criteria is allowed
