### ISSUE TITLE
Conflicts with shinyWidgets

### ISSUE THREAD

**Issue by JonP-16** [datavisyn/lineup_htmlwidget#15]
Hi!

I'm trying to use your package in my shiny application and found that it doesn't seem to display data when any command from shinyWidgets is invoked. I've tried updating to the latest versions of both packages but that doesn't seem to work. 

As an example: 
```R
library(shiny)
library(lineupjs)

ui <- fluidPage(
  sidebarLayout(
    
    sidebarPanel(
      shinyWidgets::awesomeRadio(
        inputId = "data_file_type",
        label = 'Select data type.',
        choices = c('Example Data' = "example_data",
                    'Upload Data'  = "upload_data"),
        inline = FALSE, status = "primary")
    ),
    
    mainPanel(
      lineupOutput("lineup1")
    )
    
  )
    
)

server <- function(input, output) {
  
  output$lineup1 <- renderLineup({
    if (input$data_file_type == 'example_data'){
      lineup(iris, options=list(rowHeight=20))
      
    } else {
      return(NULL)
      
    }
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by sgratzl** [comment]
as far as I can see it is a bad polyfill in shinyWidgets:

https://github.com/dreamRs/shinyWidgets/blob/3d1785125cc67654fb672b2bf35b1120b699b7f5/inst/assets/sweetalert2/sweetalert-bindings.js#L80-L82

I posted an issue in https://github.com/dreamRs/shinyWidgets/issues/243

**Comment by JonP-16** [comment]
Ah - my mistake for thinking it was your package. 

I just tried an older version of shinyWidgets (0.4.8 as opposed to 0.5.0) and it seems to work so I may end up doing that as a short-term solution until shinyWidgets gets fixed. 

Thank you for the prompt investigation.

**Comment by sgratzl** [comment]
the merged a PR that fixes this issue, closing this one
