### ISSUE TITLE
Another LineUp to HTMLwidget port (Candela)

### ISSUE THREAD

**Issue by zichner** [datavisyn/lineup_htmlwidget#3]
It seems that there is another port of LineUp as HTMLwidget (in _Candela_, which is an open-source suite of interoperable web visualization components for _Kitware_‘s _Resonant_ platform):
https://github.com/Kitware/candela
https://candela.readthedocs.io/

Might be worth to look into possible synergies.

**Comment by mstreit** [comment]
Ah, cool. Thanks for letting us know.
