### ISSUE TITLE
Purpose of small arrows and how to turn them off

### ISSUE THREAD

**Issue by nevrome** [datavisyn/lineup_htmlwidget#8]
Thanks for this really nice widget!

What's the purpose of these small up and down arrows that accompany every cell?

![screenshot_2018-10-12_16-41-51](https://user-images.githubusercontent.com/10789038/46876345-66099b80-ce3e-11e8-9163-54cd50c5e0ed.png)

How can I turn them off if they don't serve any purpose for me?

**Comment by sgratzl** [comment]
those are tiny scrollbars. We don't know yet why on some systems and configurations they appear and in others they won't. However, increasing the height of an individual row usually fixed the problem. 

can you try to run something like: 
```R
lineup(shared_iris, options=list(rowHeight=20))
```

**Comment by nevrome** [comment]
Thanks for the fast reply. Unfortunately `rowHeight` doesn't seem to do anything. I can't see any effect of this option. 

The arrows do not appear if I use `lineupjs::lineup` independently. The problem seems to be limited to the context of my shiny app. There I have some custom CSS to make some parts of the lineup table transparent.

```
.lu-row {
  background-color: rgba(0,0,0,0.0) !important;
}
.lu-header {
  background-color: rgba(0,0,0,0.0) !important;
}
.lu-handle {
  background-color: rgba(0,0,0,0.0) !important;
}
```

But I guess that's not the problem.

**Comment by nevrome** [comment]
I was able to set the row height manually in my CSS:

```
.lu-row {
  background-color: rgba(0,0,0,0.0) !important;
  height: 20px !important;
}
```

That worked and solved the scrollbar problem. Thanks for your help!

**Comment by sgratzl** [comment]
> .lu-row { background-color: rgba(0,0,0,0.0) !important; height: 20px !important; }

please avoid setting the height manually. LineUp needs to know what the row height is since it optimized the rendering to show only the visible rows. With this approach you might end up with scrolling articfacts. You can try to set `overflow: hidden !important` instead;

**Comment by nevrome** [comment]
Hm... I understand. `overflow: hidden !important` doesn't work for me. 

Do you have an idea why the rowHeight option has no effect? In the R help `?lineup` this option is not explicitly documented. Maybe it's not implemented yet on the R site?

**Comment by sgratzl** [comment]
there was a bug when merging the default options with the given options. Fixed with https://github.com/datavisyn/lineup_htmlwidget/commit/39a9acbf329105de614b4de225457e19b6d05edf. Moreover, I updated to lineupjs 3.1.5

```R
lineup(iris, options=list(rowHeight=40))
```
results now in 

![image](https://user-images.githubusercontent.com/4129778/46947114-1ca59000-d07a-11e8-814d-9cf66d31f05e.png)

**Comment by nevrome** [comment]
Excellent! Thank you very much!
